apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pro

resources:
  - ../../base

images:
  - name: registry.localtest.me:5111/sample-api
    newTag: 2f56828891a4

patches:
  - path: ingress-host.yaml
  - path: resources.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/instance: sample-api-pro
